compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: none
  deepspeed_exclusion_filter: ''
  deepspeed_hostfile: ''
  deepspeed_inclusion_filter: ''
  deepspeed_moe_layer_cls_names: ''
  deepspeed_multinode_launcher: pdsh
  zero3_init_flag: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_process_ip: 192.168.100.11
main_process_port: 29500
main_training_function: main
num_machines: 2
num_processes: 16
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
